#ifndef INCLUDE_BOT_JSON_DATA_TYPE
#define INCLUDE_BOT_JSON_DATA_TYPE

namespace bot {

enum JsonDataType {
    JSONTYPE_INT,
    JSONTYPE_FLOAT,
    JSONTYPE_BOOL,
    JSONTYPE_DOUBLE,
    JSONTYPE_STRING,
    JSONTYPE_INT_ARRAY,
    JSONTYPE_FLOAT_ARRAY,
    JSONTYPE_BOOL_ARRAY,
    JSONTYPE_DOUBLE_ARRAY,
    JSONTYPE_STRING_ARRAY
};

} // end of namespace bot

#endif
