#ifndef INCLUDE_BOT_GAME_OBJECT_TYPE
#define INCLUDE_BOT_GAME_OBJECT_TYPE

namespace bot {

enum GameObjectType {
    GAME_OBJ_TYPE_ROBOT,
    GAME_OBJ_TYPE_TILE,
    GAME_OBJ_TYPE_MISSILE,
    GAME_OBJ_TYPE_ANIMATION,
    GAME_OBJ_TYPE_PARTICLE_EFFECT,
    GAME_OBJ_TYPE_GOODIE,
    GAME_OBJ_TYPE_UNKNONWN
};

} // end of namespace bot

#endif
